name: DevOps CI

on:

  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:

  validate:

    runs-on: self-hosted

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Validate Docker Compose
        run: docker compose config

      - name: Validate Dockerfile
        run: docker build -t test-nginx ./docker/nginx

      - name: Validate Inventory
        run: ansible-inventory -i ansible/inventory.ini --list

      - name: Validate Playbook
        run: ansible-playbook -i ansible/inventory.ini ansible/deploy.yml --syntax-check

      - name: Validate Jenkinsfile
        run: test -f Jenkinsfile

      - name: Trigger Jenkins Pipeline
        run: |
          STATE="present"

          if [[ "${{ github.event.head_commit.message }}" =~ "absent" || "${{ github.event.head_commit.message }}" =~ "desinstalar" ]]; then
            STATE="absent"
          fi

          echo "El estado enviado a Jenkins será: $STATE"

          CRUMB=$(curl -s "http://localhost:8080/crumbIssuer/api/json" --user "admin:${{ secrets.JENKINS_USER_TOKEN }}" | grep -o '"crumb":"[^"]*' | sed 's/"crumb":"//' | xargs -I {} echo "Jenkins-Crumb:{}")
          curl -X POST -H "$CRUMB" "http://localhost:8080/job/devops-project/buildWithParameters?PACKAGE_NAME=htop&PACKAGE_STATE=${STATE}&token=${{ secrets.JENKINS_JOB_TOKEN }}" --user "admin:${{ secrets.JENKINS_USER_TOKEN }}" --data-urlencode "json={}"
