name: DevOps CI

on:

  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:

  validate:

    runs-on: self-hosted

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Validate Docker Compose
        run: docker compose config

      - name: Validate Dockerfile
        run: docker build -t test-nginx ./docker/nginx

      - name: Validate Inventory
        run: ansible-inventory -i ansible/inventory.ini --list

      - name: Validate Playbook
        run: ansible-playbook -i ansible/inventory.ini ansible/deploy.yml --syntax-check

      - name: Validate Jenkinsfile
        run: test -f Jenkinsfile
      - name: Trigger Jenkins Pipeline
        run: curl -X POST "http://localhost:8080/job/devops-project/buildWithParameters?PACKAGE_NAME=htop&PACKAGE_STATE=present&token=${{ secrets.JENKINS_JOB_TOKEN }}" --user "admin:${{ secrets.JENKINS_USER_TOKEN }}"--data-urlencode json={}
